In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('original.csv')
df = df.fillna(0)
df['x2'] = df.apply(lambda row: row['width'] + row['x'], axis=1)
df['y2'] = df.apply(lambda row: row['height'] + row['y'], axis=1)
df = df.astype({
    'x': int,
    'y': int,
    'x2': int,
    'y2': int
})
df = df[['Id', 'x', 'y', 'x2', 'y2', 'Target']]
df.columns = ['Id', 'x1', 'y1', 'x2', 'y2', 'Pneumonia']
df

                                         Id   x1   y1   x2   y2  Pneumonia
0      0004cfab-14fd-4e49-80ba-63a80b6bddd6    0    0    0    0          0
1      00313ee0-9eaa-42f4-b0ab-c148ed3241cd    0    0    0    0          0
2      00322d4d-1c29-4943-afc9-b6754be640eb    0    0    0    0          0
3      003d8fa0-6bf1-40ed-b54c-ac657f8495c5    0    0    0    0          0
4      00436515-870c-4b36-a041-de91049b9ab4  264  152  477  531          1
...                                     ...  ...  ...  ...  ...        ...
30222  c1ec14ff-f6d7-4b38-b0cb-fe07041cbdc8  185  298  413  677          1
30223  c1edf42b-5958-47ff-a1e7-4f23d99583ba    0    0    0    0          0
30224  c1f6b555-2eb1-4231-98f6-50a963976431    0    0    0    0          0
30225  c1f7889a-9ea9-4acb-b64c-b737c929599a  570  393  831  738          1
30226  c1f7889a-9ea9-4acb-b64c-b737c929599a  233  424  434  780          1

[30227 rows x 6 columns]

In [3]:
df.to_csv('info.csv', index=False)